In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [13]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [9]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arr_2d = np.arange(5, 50, 5).reshape(3, 3)

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])