In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:, 4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:, 0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaler_object = MinMaxScaler()

In [14]:
scaler_object.fit(X_train)

MinMaxScaler()

In [15]:
scaled_X_train = scaler_object.transform(X_train)

In [16]:
scaled_X_test = scaler_object.transform(X_test)

In [17]:
scaled_X_train.max()

1.0000000000000002

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))  # Input layer
model.add(Dense(8, activation='relu'))  # Hidden Layer
model.add(Dense(1, activation='sigmoid'))  # Output layer

# After the network setup, then we'll compile our model.
# For compilation, we need to choose a loss, an optimizer and the metrics we are concerned with.

In [22]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [23]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.6837 - accuracy: 0.5495 - 586ms/epoch - 20ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6740 - accuracy: 0.5495 - 52ms/epoch - 2ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6692 - accuracy: 0.5495 - 30ms/epoch - 1ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6660 - accuracy: 0.5495 - 31ms/epoch - 1ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6620 - accuracy: 0.5495 - 31ms/epoch - 1ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6582 - accuracy: 0.5495 - 34ms/epoch - 1ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6539 - accuracy: 0.5495 - 38ms/epoch - 1ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6447 - accuracy: 0.5495 - 43ms/epoch - 1ms/step
Epoch 9/50
29/29 - 0s - loss: 0.6291 - accuracy: 0.5550 - 41ms/epoch - 1ms/step
Epoch 10/50
29/29 - 0s - loss: 0.6159 - accuracy: 0.5876 - 45ms/epoch - 2ms/step
Epoch 11/50
29/29 - 0s - loss: 0.6016 - accuracy: 0.6104 - 54ms/epoch - 2ms/step
Epoch 12/50
29/29 - 0s - loss: 0.5863 - accuracy: 0.6518 - 46ms/epoch - 2ms/step
Epoch 13/50
29/29 - 0s - loss: 0.57

In [33]:
# predictions = model.predict(scaled_X_test)
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 905us/step


In [34]:
predictions

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [35]:
model.metrics_names

['loss', 'accuracy']

In [36]:
from sklearn.metrics import confusion_matrix, classification_report

In [37]:
confusion_matrix(y_test, predictions)

array([[251,   6],
       [ 10, 186]])

In [39]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97       257
         1.0       0.97      0.95      0.96       196

    accuracy                           0.96       453
   macro avg       0.97      0.96      0.96       453
weighted avg       0.96      0.96      0.96       453



In [40]:
model.save('mysupermodel.h5')

In [41]:
from keras.models import load_model

In [42]:
newmodel = load_model('mysupermodel.h5')

In [43]:
(newmodel.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 974us/step


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    